version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: zixly-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=zixly_admin
      - POSTGRES_PASSWORD=local_dev_password
      - POSTGRES_DB=zixly_main
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - zixly-local
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U zixly_admin -d zixly_main']
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: zixly-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass local_dev_password
    ports:
      - '6380:6379'
    volumes:
      - redis_data:/data
    networks:
      - zixly-local
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3

  # pipeline Workflow Automation
  pipeline:
    image: pipelineio/pipeline:latest
    container_name: zixly-pipeline
    restart: unless-stopped
    environment:
      - PIPELINE_HOST=localhost
      - PIPELINE_PORT=5678
      - PIPELINE_BASIC_AUTH_ACTIVE=true
      - PIPELINE_BASIC_AUTH_USER=cole.morton@hotmail.com
      - PIPELINE_BASIC_AUTH_PASSWORD=Password1
      - DB_TYPE=sqlite
      - DB_SQLITE_DATABASE=/home/node/.pipeline/database.sqlite
      - PIPELINE_ENCRYPTION_KEY=zixly-local-encryption-key-2024
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=168
    ports:
      - '5678:5678'
    volumes:
      - pipeline_data:/home/node/.pipeline
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - zixly-local
    healthcheck:
      test:
        ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:5678/healthz']
      interval: 30s
      timeout: 10s
      retries: 3

  # Plane Project Management (commented out - image not available)
  # plane:
  #   image: makeplane/plane:latest
  #   container_name: zixly-plane
  #   restart: unless-stopped
  #   environment:
  #     - DATABASE_URL=postgresql://zixly_admin:local_dev_password@postgres:5432/plane
  #     - REDIS_URL=redis://:local_dev_password@redis:6379
  #     - SECRET_KEY=local_plane_secret_key
  #     - WEB_URL=http://localhost:8000
  #     - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
  #   ports:
  #     - '8000:8000'
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #   networks:
  #     - zixly-local
  #   healthcheck:
  #     test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:8000/health']
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pipeline_data:
    driver: local

networks:
  zixly-local:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
