global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'alerts.yml'

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Trading API
  - job_name: 'trading-api'
    static_configs:
      - targets: ['trading-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Webhook Receiver
  - job_name: 'webhook-receiver'
    static_configs:
      - targets: ['webhook-receiver:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Pipeline Workers
  - job_name: 'pipeline-worker'
    dns_sd_configs:
      - names: ['pipeline-worker']
        type: 'A'
        port: 3000
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Next.js App (if metrics enabled)
  - job_name: 'nextjs-app'
    static_configs:
      - targets: ['nextjs-app:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # LocalStack (if metrics enabled)
  - job_name: 'localstack'
    static_configs:
      - targets: ['localstack:4566']
    metrics_path: '/metrics'
    scrape_interval: 60s
    scrape_timeout: 10s

  # PostgreSQL (if metrics enabled)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 60s
    scrape_timeout: 10s
